// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "fizzbuzz/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// StatsRepository is an autogenerated mock type for the StatsRepository type
type StatsRepository struct {
	mock.Mock
}

type StatsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *StatsRepository) EXPECT() *StatsRepository_Expecter {
	return &StatsRepository_Expecter{mock: &_m.Mock}
}

// IncrementHit provides a mock function with given fields: ctx, req
func (_m *StatsRepository) IncrementHit(ctx context.Context, req domain.FizzBuzzRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for IncrementHit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.FizzBuzzRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StatsRepository_IncrementHit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementHit'
type StatsRepository_IncrementHit_Call struct {
	*mock.Call
}

// IncrementHit is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.FizzBuzzRequest
func (_e *StatsRepository_Expecter) IncrementHit(ctx interface{}, req interface{}) *StatsRepository_IncrementHit_Call {
	return &StatsRepository_IncrementHit_Call{Call: _e.mock.On("IncrementHit", ctx, req)}
}

func (_c *StatsRepository_IncrementHit_Call) Run(run func(ctx context.Context, req domain.FizzBuzzRequest)) *StatsRepository_IncrementHit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.FizzBuzzRequest))
	})
	return _c
}

func (_c *StatsRepository_IncrementHit_Call) Return(_a0 error) *StatsRepository_IncrementHit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StatsRepository_IncrementHit_Call) RunAndReturn(run func(context.Context, domain.FizzBuzzRequest) error) *StatsRepository_IncrementHit_Call {
	_c.Call.Return(run)
	return _c
}

// MostFrequent provides a mock function with given fields: ctx
func (_m *StatsRepository) MostFrequent(ctx context.Context) (*domain.StatEntry, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for MostFrequent")
	}

	var r0 *domain.StatEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.StatEntry, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.StatEntry); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StatEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatsRepository_MostFrequent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MostFrequent'
type StatsRepository_MostFrequent_Call struct {
	*mock.Call
}

// MostFrequent is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StatsRepository_Expecter) MostFrequent(ctx interface{}) *StatsRepository_MostFrequent_Call {
	return &StatsRepository_MostFrequent_Call{Call: _e.mock.On("MostFrequent", ctx)}
}

func (_c *StatsRepository_MostFrequent_Call) Run(run func(ctx context.Context)) *StatsRepository_MostFrequent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *StatsRepository_MostFrequent_Call) Return(_a0 *domain.StatEntry, _a1 error) *StatsRepository_MostFrequent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StatsRepository_MostFrequent_Call) RunAndReturn(run func(context.Context) (*domain.StatEntry, error)) *StatsRepository_MostFrequent_Call {
	_c.Call.Return(run)
	return _c
}

// NewStatsRepository creates a new instance of StatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatsRepository {
	mock := &StatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
