// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "fizzbuzz/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// FizzBuzzExecutor is an autogenerated mock type for the FizzBuzzExecutor type
type FizzBuzzExecutor struct {
	mock.Mock
}

type FizzBuzzExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *FizzBuzzExecutor) EXPECT() *FizzBuzzExecutor_Expecter {
	return &FizzBuzzExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, req
func (_m *FizzBuzzExecutor) Execute(ctx context.Context, req domain.FizzBuzzRequest) ([]string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.FizzBuzzRequest) ([]string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.FizzBuzzRequest) []string); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.FizzBuzzRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FizzBuzzExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type FizzBuzzExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.FizzBuzzRequest
func (_e *FizzBuzzExecutor_Expecter) Execute(ctx interface{}, req interface{}) *FizzBuzzExecutor_Execute_Call {
	return &FizzBuzzExecutor_Execute_Call{Call: _e.mock.On("Execute", ctx, req)}
}

func (_c *FizzBuzzExecutor_Execute_Call) Run(run func(ctx context.Context, req domain.FizzBuzzRequest)) *FizzBuzzExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.FizzBuzzRequest))
	})
	return _c
}

func (_c *FizzBuzzExecutor_Execute_Call) Return(_a0 []string, _a1 error) *FizzBuzzExecutor_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FizzBuzzExecutor_Execute_Call) RunAndReturn(run func(context.Context, domain.FizzBuzzRequest) ([]string, error)) *FizzBuzzExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewFizzBuzzExecutor creates a new instance of FizzBuzzExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFizzBuzzExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *FizzBuzzExecutor {
	mock := &FizzBuzzExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
