// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "fizzbuzz/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// StatsQuery is an autogenerated mock type for the StatsQuery type
type StatsQuery struct {
	mock.Mock
}

type StatsQuery_Expecter struct {
	mock *mock.Mock
}

func (_m *StatsQuery) EXPECT() *StatsQuery_Expecter {
	return &StatsQuery_Expecter{mock: &_m.Mock}
}

// MostFrequent provides a mock function with given fields: ctx
func (_m *StatsQuery) MostFrequent(ctx context.Context) (*domain.StatEntry, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for MostFrequent")
	}

	var r0 *domain.StatEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.StatEntry, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.StatEntry); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StatEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatsQuery_MostFrequent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MostFrequent'
type StatsQuery_MostFrequent_Call struct {
	*mock.Call
}

// MostFrequent is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StatsQuery_Expecter) MostFrequent(ctx interface{}) *StatsQuery_MostFrequent_Call {
	return &StatsQuery_MostFrequent_Call{Call: _e.mock.On("MostFrequent", ctx)}
}

func (_c *StatsQuery_MostFrequent_Call) Run(run func(ctx context.Context)) *StatsQuery_MostFrequent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *StatsQuery_MostFrequent_Call) Return(_a0 *domain.StatEntry, _a1 error) *StatsQuery_MostFrequent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StatsQuery_MostFrequent_Call) RunAndReturn(run func(context.Context) (*domain.StatEntry, error)) *StatsQuery_MostFrequent_Call {
	_c.Call.Return(run)
	return _c
}

// NewStatsQuery creates a new instance of StatsQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatsQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatsQuery {
	mock := &StatsQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
